### ISSUE TITLE
0.5 value is transformed into 5

### ISSUE THREAD

**Issue by Tom-Spring** [figueiredorui/1-click-tasks#11]
Hi Rui

I have just found a minor glitch.  If for example the field "remaining work" is set to 0.5 in a task template. That task will be created with "remaining work" 5 instead of 0.5 when using one click tasks to create the task.

Best Regards

Tom

**Comment by figueiredorui** [comment]
Hi Tom, 
I managed to reproduce this behavior using comma (0,5) instead of point(0.5) for decimal separator.
Using 0.5 works fine for me.

Regards,
