### ISSUE TITLE
Doesn't seem to work with TFS 2015; nothing seems to happen on clicking '1-Click tasks'

### ISSUE THREAD

**Issue by jsingla** [figueiredorui/1-click-tasks#12]
Version: 0.6.0
Installed on: TFS 2015

Steps followed:
1. Created task templates in Visual Studio
![screen shot 2017-03-22 at 2 21 20 am](https://cloud.githubusercontent.com/assets/1568002/24179386/b04c9e4e-0ea6-11e7-92b1-8af7770a47fd.png)

2. Was able to add tasks using the templates in TFS
![screen shot 2017-03-22 at 2 23 41 am](https://cloud.githubusercontent.com/assets/1568002/24179390/b9a89e7a-0ea6-11e7-9fff-65a0f58b8c63.png)

3. Tried using 1-Click tasks option in the TFS web portal but nothing happens on clicking it
![screen shot 2017-03-22 at 2 23 56 am](https://cloud.githubusercontent.com/assets/1568002/24179392/be820404-0ea6-11e7-9413-4c17c61fe351.png)

**Comment by jsingla** [comment]
Hi,

This is a really useful extension but unfortunately can't seem to get it working on TFS 2015. I've logged the bug report above. Could you please have a look.

Thanks.

**Comment by figueiredorui** [comment]
Hi,
Could you check browser console errors?

**Comment by jsingla** [comment]
It's returning 401, so possibly a permissions issue, but not sure where to look to resolve it (please see attached snapshot).
![tfs tasks](https://cloud.githubusercontent.com/assets/1568002/25011287/c398e47e-2064-11e7-970a-9fbb383a6ddc.png)

**Comment by jsingla** [comment]
Upgraded to TFS 2017 Update 1 and the issue isn't happening in that version. Therefore, closing this issue.
