### ISSUE TITLE
Please don't set the Assigned To field

### ISSUE THREAD

**Issue by rhundhausen** [figueiredorui/1-click-tasks#15]
Dear Product Owner,

As a user of your template on a Scrum team,
I want it to *not* set the assigned-to field to the person running the keyboard,
so that we can enjoy self-organization as we pull tasks and own them throughout the sprint.

For more details, see "Don't lick the cookie" (https://www.benday.com/2016/10/21/scrum-dont-lick-the-cookie)

Thank you.

**Comment by figueiredorui** [comment]
Hi @rhundhausen, I have changed the logic that populates the AssignTo Field.
The AssignTo field only gets populate when exists in the template.
It allows the value @me to assign the task to the current user or when left empty it copies the AssignTo value from the parent.

**Comment by rhundhausen** [comment]
Good news. Thank you.

**Comment by HasanlouM** [comment]
Dear @figueiredorui 

I add the AssignTo field in the template and left it empty to copies the AssignTo value from the parent, but it doesn't work.

**Comment by accentient** [comment]
The entire extension doesn't work any longer. I'm recommending to my clients to uninstall it unless @figueiredorui gives us some good news!
