### ISSUE TITLE
Any plan to distinguish task sets?

### ISSUE THREAD

**Issue by jdshkolnik** [figueiredorui/1-click-tasks#2]
Hi,

Do you plan to distinguish task sets so we can create a subset in a single click instead of all? Perhaps by description?

**Comment by figueiredorui** [comment]
That's a good idea. I'll implement an optional identifier on the template name to distinguish what task templates are added for Stories, Bugs or both.

**Comment by jdshkolnik** [comment]
@figueiredorui Are you thinking some sort of prefix? That might not be as flexible if you want to use the same task in multiple sets. Something tag-based might be more powerful, like {{set1,set2,etc.}}

**Comment by figueiredorui** [comment]
@jdshkolnik 

I have implemented a way of having an identifier to distinguish which tasks should be added to work items.
I've used the description to specify the identifiers.

![image](https://cloud.githubusercontent.com/assets/5295139/22847932/72e71944-efe8-11e6-89ad-ea1a19338e6f.png)

**Comment by jdshkolnik** [comment]
@figueiredorui That's awesome! Can a single template apply to multiple work item types? Would it be [Product Backlog Item,Bug]?

**Comment by figueiredorui** [comment]
@jdshkolnik yes, the [A, B, C] pattern can be used to apply template to multiple work items and if nothing specified it applies to all work items.

**Comment by hugoverheyen** [comment]
Is this feature already released ?

**Comment by figueiredorui** [comment]
@hugoverheyen, yes, this feature has already been released
