### ISSUE TITLE
Licensing terms missing

### ISSUE THREAD

**Issue by BorisUK** [figueiredorui/1-click-tasks#22]
Hello,

We are planning to use the [1-Click Tasks extension for VSTS](https://marketplace.visualstudio.com/items?itemName=ruifig.vsts-work-item-one-click-tasks&targetId=5f22a025-b310-4483-bb27-d8b98fb03a0e&utm_source=vstsproduct&utm_medium=ExtHubManageList#overview).

Could you please provide us with a copy of the licence terms this extension is licensed under? Normally this is accessible via a Licence link on the extensions page, but in case of this extensions I can’t find the link.

Thanks
Boris

**Comment by figueiredorui** [comment]
You can find the license here 
https://github.com/figueiredorui/1-click-tasks/blob/master/LICENSE

**Comment by BorisUK** [comment]
Thanks for doing this so quickly
