### ISSUE TITLE
Can't get this to work on VSTS for User Stories or Bugs

### ISSUE THREAD

**Issue by jmsvl** [figueiredorui/1-click-tasks#3]
Hi, I can't get this extension to work on VSTS for User Stories or Bugs. In Chrome and with a project with more than one Area (only one of the areas has the task templates).

Can you help? Nothing on console (I saw that console log is commented out on source code) and not even the loading icon appears

**Comment by figueiredorui** [comment]
Hi Jorge, there was an issue with AreaPath field. I've have fixed it and I've done other improvements as well.
