### ISSUE TITLE
Fails to create task if a field contains a calculated variable such as @CurrentIteration

### ISSUE THREAD

**Issue by CSharpGuy2006** [figueiredorui/1-click-tasks#32]
If the pre-defined template task has a field which uses @CurrentIteration as it's value, the task is not created.  When you remove that assignment to a static value or remove alltogether, the 1-click works as expected.

to recreate:
1. create template task with title and save
2. open a User Story and use 1-click to add task
3. once it finishes, delete task and save.
4. modify template task and add field Iteration with @CurrentIteration as default and save
2 open User Story and use 1-click to add task.

Result, no task is added.

go back to template and either remove or make that field static and save
go back to User Story and 1-click works.

Great plugin, I really appreciate it!

**Comment by figueiredorui** [comment]
@CurrentIteration is not supported
