### ISSUE TITLE
Add Add hierarchy for Epics and Features

### ISSUE THREAD

**Issue by HeroMaxPower** [figueiredorui/1-click-tasks#4]
Enhancement: For businesses this could be great for predefined epics with mandatory features and features that have predefined mandatory PBI’s/User Stories.

1 Click task could add templates from Features to 1 Epic
1 Click task could add templates for PBI’s/User to 1 Feature

**Comment by figueiredorui** [comment]
Hi, thanks for your suggestion. 
I have created a new extension, please check 
[1-Click Child-Links](https://marketplace.visualstudio.com/items?itemName=ruifig.vsts-work-item-one-click-child-links)
