### ISSUE TITLE
Does not work on TFS 2017

### ISSUE THREAD

**Issue by alkeshp** [figueiredorui/1-click-tasks#5]
I have installed the extension on TFS 2017. 
Setup about 12 default Tasks in the Task templates settings.
But when I create a new user story and click on 1-clck-tasks, then nothing happens.

**Comment by jdshkolnik** [comment]
Hi @alkeshp,

Maybe I can help. I have it working on my TFS 2017 instance so it may be something particular to yours. Can you post a screenshot? Do you see any errors in the Chrome debugger?

**Comment by figueiredorui** [comment]
Thanks for look into this.

**Comment by alkeshp** [comment]
HI John,
Thanks for helping. Attached is the Chrome debugger screenshot.
Screen below shows that after I click on 1-click tasks, no related work items were created.

[cid:image001.jpg@01D25462.5FE447D0]

**Comment by alkeshp** [comment]
Hi Rui,
Attached is the Chrome debugger screenshot.
Screen below shows that after I click on 1-click tasks, no related work items were created.

[cid:image001.jpg@01D25462.ADE96CD0]

**Comment by alkeshp** [comment]
![one-click error2](https://cloud.githubusercontent.com/assets/24475711/21092755/fa3d0870-c056-11e6-917a-b5723a00f00d.png)

**Comment by alkeshp** [comment]
<img width="647" alt="one-click error1" src="https://cloud.githubusercontent.com/assets/24475711/21092827/52b38c72-c057-11e6-8f55-c2410262ce2b.png">

**Comment by figueiredorui** [comment]
I've managed to reproduce issue and I've fixed the bug.

**Comment by figueiredorui** [comment]
By the way, check an enhanced version of this extension that allow to create child links for any kind of Work Item [1-Click Child-Links ](https://marketplace.visualstudio.com/items?itemName=ruifig.vsts-work-item-one-click-child-links)

**Comment by jdshkolnik** [comment]
@figueiredorui How does it differ from the original?

**Comment by figueiredorui** [comment]
1-Click Tasks only adds tasks to User Stories/Bug. 
1-Click Child-Links adds childs to  any kind of work item, i.e., when you looking at an Epic, it adds predefined Feature templates, for an Feature it adds predefined Bugs, Stories templates, etc...
It follows the process workflow
![w](https://cloud.githubusercontent.com/assets/5295139/21119301/d8612250-c0b9-11e6-9377-a1cbadd96ef5.png)

**Comment by jdshkolnik** [comment]
@figueiredorui I see. I'll hold off until it can be a targeted subset.

**Comment by alkeshp** [comment]
Great, works brilliant, thank you!
