### ISSUE TITLE
HTTP 401 status (tfs 2017)

### ISSUE THREAD

**Issue by GersonDias** [figueiredorui/1-click-tasks#6]
I'm trying to use this extension on TFS 2017, but I'm receiving a 401 Unauthorized status when I click on button. I tried 1-Click Create Tasks and 1-Click Create Child-Links extension.

![image](https://cloud.githubusercontent.com/assets/1994582/21230088/f452cdac-c2ca-11e6-80f5-a9cb4ef194ae.png)

**Comment by figueiredorui** [comment]
Hi Gerson,

Thanks for your feedback. 
I haven't had a chance of testing it on TFS 2017 yet. Other users reported that being working on TFS 2017, [Doesn't work on TFS 2017](https://github.com/figueiredorui/1-click-tasks/issues/1), [Does not work on TFS 2017](https://github.com/figueiredorui/1-click-tasks/issues/5).
I plan to test it on TFS 2017 soon. 
Let me know if the problem persists.
