### ISSUE TITLE
Create tasks in alphabetical order

### ISSUE THREAD

**Issue by jdshkolnik** [figueiredorui/1-click-tasks#7]
It seems to create the tasks in a random order each time.

**Comment by figueiredorui** [comment]
I don't have that behaviour. The tasks are created with the same order as they appear on Task templates list.

**Comment by jdshkolnik** [comment]
The task templates list is alphabetical yet the tasks created by 1-click are not. Furthermore, the tasks created by 1-click aren't created in the same consistent order from one to the next.

**Comment by figueiredorui** [comment]
Have released a new version to enforce creation of task alphabetically, although, during my tests I have notice that the tasks on the Work item, they are listed ordered by User then by Title.
![image](https://cloud.githubusercontent.com/assets/5295139/22082511/f9d5b1f8-ddbf-11e6-824c-33560da111f7.png)

**Comment by jdshkolnik** [comment]
Thank you.
