### ISSUE TITLE
Only Working For One User

### ISSUE THREAD

**Issue by mnmksolomon** [figueiredorui/1-click-tasks#8]
I've installed the extension and it's working great, but only for my user in VSTS. Is there something that I have to do in order for it to work globally across the VSTS project?

**Comment by figueiredorui** [comment]
Hi, 
Thanks for your feedback. 
When you say it's not working for other users, you mean they don't see the '1-click-tasks' option on the menu or they click the option and nothing happens?

Rui

**Comment by mnmksolomon** [comment]
They have the option but when they click it nothing happens, even after a refresh.

[MNM Logo]


Kim Solomon, Scrum Master
Mercury New Media
O: 813.933.9800 ext. 2417
F: 813.354.2596
ksolomon@mercurynewmedia.com<mailto:ksolomon@mercurynewmedia.com>
www.mercurynewmedia.com<http://www.mercurynewmedia.com/>

**Comment by figueiredorui** [comment]
@mnmksolomon Could you check if any error on Dev Tools Console.

**Comment by mnmksolomon** [comment]
I don’t know how to do that.

[MNM Logo]


Kim Solomon, Scrum Master
Mercury New Media
O: 813.933.9800 ext. 2417
F: 813.354.2596
ksolomon@mercurynewmedia.com<mailto:ksolomon@mercurynewmedia.com>
www.mercurynewmedia.com<http://www.mercurynewmedia.com/>

**Comment by figueiredorui** [comment]
[Dev tools](https://developers.google.com/web/tools/chrome-devtools/) look for console tab.
leave it open while clicking  '1-click-tasks'

**Comment by mnmksolomon** [comment]
I did not get an error. I have requested another user to do the same since the extension historically works for me.

Standby.

[MNM Logo]


Kim Solomon, Scrum Master
Mercury New Media
O: 813.933.9800 ext. 2417
F: 813.354.2596
ksolomon@mercurynewmedia.com<mailto:ksolomon@mercurynewmedia.com>
www.mercurynewmedia.com<http://www.mercurynewmedia.com/>

**Comment by mnmksolomon** [comment]
This is what other users are receiving, “workItemType is not defined.”

[cid:image002.png@01D282E3.FF81A800]

[MNM Logo]


Kim Solomon, Scrum Master
Mercury New Media
O: 813.933.9800 ext. 2417
F: 813.354.2596
ksolomon@mercurynewmedia.com<mailto:ksolomon@mercurynewmedia.com>
www.mercurynewmedia.com<http://www.mercurynewmedia.com/>

**Comment by figueiredorui** [comment]
I haven't received the attached image.
Could you reply on GitHub instead of replying to the email.

**Comment by mnmksolomon** [comment]
![1-click dev tools error](https://cloud.githubusercontent.com/assets/25612589/22803233/1d217d58-eee2-11e6-8fb9-a339a2cc8448.png)

**Comment by figueiredorui** [comment]
I have fixed this issue, now you should see a proper message box.
It looks like the other users belong to a team that doesn't have templates defined.

**Comment by mnmksolomon** [comment]
Is there a way to make these templates global to the project?
